# Generated by Django 5.2.6 on 2025-09-27 00:52

import xlstoxlsx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to=xlstoxlsx.models.upload_to,
                        verbose_name="Archivo Original (.xls)",
                    ),
                ),
                (
                    "converted_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="converted/",
                        verbose_name="Archivo Convertido (.xlsx)",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del archivo original"
                    ),
                ),
                (
                    "converted_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del archivo convertido",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de conversión"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tamaño del archivo (bytes)"
                    ),
                ),
                (
                    "conversion_successful",
                    models.BooleanField(
                        default=False, verbose_name="Conversión exitosa"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Conversión",
                "verbose_name_plural": "Registros de Conversiones",
                "ordering": ["-created_at"],
            },
        ),
    ]
